<!-- 
Created by: 		Nemanja Grubor
Date: 				2018-12-07
Project: 			Multiplication table
Description:		A simple project that demonstrates an operation of multiplication of a pair of positive integers between 1 and 10, stored in a table.
Completion time:	Five hours				
-->
<!-- -->
<!-- Operation of multiplication is stored in calculator.class.php file-->
<?php include_once('calculator.class.php'); ?>

<!--config.php file contains a connection parameters to MySQL database. On user request, multiplication result is stored in a database table. -->
<?php include_once('config.php'); ?>

<!-- HTML  -->
<!DOCTYPE html>
<html>
<head>
    <title>Task :: Multiplication Table</title>
	<link href="style.css" rel="stylesheet" type="text/css">
</head>
<body>

<!-- php code that
1. turns off error reporting because of initial warnings generated by inability of code to manipulate with null values. By turning it off, the functionality is not damaged.
2. generates a 10 by 10 table. Table cells store factors of multiplication as links.  -->
    <?php
	error_reporting(0);
    echo "<table id=\"table0\" border =\"1\" style='border-collapse: collapse'>";
    for ($row=1; $row <= 10; $row++) { 
        echo "<tr> \n";
        for ($col=1; $col <= 10; $col++) { 
           $a = "$row * $col";
           echo "<td><a href=?row=$row&col=$col>".$a;
           echo "</a></td> \n";
        }
        echo "</tr>";
    }
    echo "</table>";
    ?>
	
	<div>
<!-- Variables factor1 and factor2 are used in insert into sql query to make code more readable. -->
		<?php $factor1=$_GET['row'] ?>
		<?php $factor2=$_GET['col'] ?>
		
<!-- On cell value click, the following code calculates the result of multiplication by using calculate function (stored in a separated class file), and writes the result in a result1 field -->				
		<input id="result1" type="text" value="<?php if( (isset($_GET['col']) && $_GET['row'])){ echo $result=Calculator::calculate($_GET['row'],$_GET['col']);} ?>" disabled >	
	</div>

<!-- A button to insert the result and factors of multiplication in the database. It also stores current DATETIME value generated by button click. 
The idea is to limit a user to insert results of unwilling clicks into the database.-->
	<form action="#" method="post">
	<input type="submit" name="insert" class="button" value="INSERT INTO DATABASE" />
	</form>

<!-- php code that 
1. gets current DATETIME value from the php server.
2. if the privilege of insert is allowed on a database, then sql query is executed in a way that selected factors and calculated result are forwarded as parameters.
   Current DATETIME is a parameter of the SQL.
3. The message of sql successful execution is written as well as a message in a case of error. -->	
	<?php
	$sql_date=date('Y-m-d H:i:s');
	
	if($_SERVER['REQUEST_METHOD'] == "POST" and isset($_POST['insert']))
	{
		require 'config.php'; 
		$sql = "INSERT INTO multiplications (factor1, factor2, operation, result, operation_date)
				VALUES (".$factor1.", ".$factor2.", '*', ".$result.", '".$sql_date."')";

		if ($conn->query($sql) === TRUE) 
			{
				echo "New record created successfully";
			}
				else 
			{
				echo "Error: " . $sql . "<br>" . $conn->error;
			}
		$conn->close();
	}
?>	

<!-- Display print of a table containing values inserted in a database. -->
<!-- Table header -->
<table id="table1">
	<tr>
		<th>ID</th>
		<th>Factor1</th>
		<th>Factor2</th>
		<th>Operation</th>
		<th>Result</th>
		<th>Operation Date</th>
	</tr>

<!-- php code to generate table cells and values. -->
<?php
require 'config.php'; 
$sql = "SELECT id, factor1, factor2, operation, result, operation_date FROM multiplications";
$result = $conn->query($sql);

if ($result->num_rows > 0) {
    while($row = $result->fetch_assoc()) {
        echo "<tr><td>" . $row["id"]. "</td><td>" . $row["factor1"]. "</td><td>" . $row["factor2"]. "</td><td>" . $row["operation"]. "</td><td>" . $row["result"]. "</td><td>" . $row["operation_date"]. "</td><tr>";
    }
} 
	else 
{
    echo "0 results";
}
$conn->close();
?>
</table>
</body>
</html>




	 